name: CI

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build:
    name: Maven Build
    if: github.ref != 'refs/heads/master' || github.repository != 'portfolio-performance/portfolio'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Cache Maven repository
      uses: actions/cache@v5
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ runner.os }}-mvn
        restore-keys: |
          ${{ runner.os }}-mvn-
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: zulu
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.11
    - name: Build with Maven
      run: |
        mvn verify \
        --batch-mode \
        --file portfolio-app/pom.xml
        set MAVEN_OPTS="-Xmx4g"
        mvn -f portfolio-app/pom.xml clean verify
      run: mkdir staging && cp target/*.jar staging
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging  

  build-analyze:
    name: Maven Build + Sonar Analysis
    if: github.ref == 'refs/heads/master' && github.repository == 'portfolio-performance/portfolio'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Cache Maven repository
      uses: actions/cache@v5
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ runner.os }}-mvn
        restore-keys: |
          ${{ runner.os }}-mvn-
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: zulu
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.11
    - name: Build with Maven
      run: |
        mvn verify sonar:sonar \
        --batch-mode \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
        --file portfolio-app/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
